
import { 
  ArrowRight, 
  Send, 
  Zap, 
  Check, 
  Cpu, 
  MessageSquare, 
  Brain, 
  Workflow, 
  Rocket, 
  Sparkles,
  Layers,
  Phone,
  Mail,
  ArrowUpRight,
  ExternalLink,
  Plus,
  Star,
  Users,
  Database,
  CheckCircle,
  Target
} from 'lucide-react';

export const Icons = {
  ArrowRight,
  Send,
  Zap,
  Check,
  Cpu,
  MessageSquare,
  Brain,
  Workflow,
  Rocket,
  Sparkles,
  Layers,
  Phone,
  Mail,
  ArrowUpRight,
  ExternalLink,
  Plus,
  Star,
  Users,
  Database,
  CheckCircle,
  Target,
  WordPress: (props: any) => <img src="https://www.svgrepo.com/show/38867/wordpress-logo.svg" {...props} />,
  Zapier: (props: any) => <img src="https://www.svgrepo.com/show/331265/zapier.svg" {...props} />,
  Asana: (props: any) => <img src="https://www.svgrepo.com/show/353425/asana.svg" {...props} />,
  Monday: (props: any) => <img src="https://www.svgrepo.com/show/354088/monday-icon.svg" {...props} />,
  Airtable: (props: any) => <img src="https://www.svgrepo.com/show/353383/airtable.svg" {...props} />,
  ClickUp: (props: any) => <img src="https://www.svgrepo.com/show/331339/clickup.svg" {...props} />,
  HubSpot: (props: any) => <img src="https://www.svgrepo.com/show/331433/hubspot.svg" {...props} />,
  Make: (props: any) => <img src="https://registry.npmmirror.com/@lobehub/icons-static-png/1.75.0/files/dark/make-color.png" {...props} />,
  N8N: (props: any) => <img src="https://registry.npmmirror.com/@lobehub/icons-static-png/1.75.0/files/dark/n8n-color.png" {...props} />,
  GoHighLevel: (props: any) => <img src="https://cdn.brandfetch.io/idK-hvK7Lv/w/200/h/200/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1692001846848" {...props} />,
  CloseBot: (props: any) => <img src="https://closebot.com/wp-content/uploads/2025/04/closebot_logo_white.svg" {...props} />,
  Pabbly: (props: any) => <img src="https://i.ibb.co/XxnFT8D2/Pabbly-Logo-Icon-SVG.jpg" {...props} />
};
